#!/usr/bin/env python3
"""Verify stress inputs, compare actual Linguist, then optionally benchmark each mode."""
# Result keys retain the original evidence format across the project rename.
import argparse
import hashlib
import json
import math
import os
from pathlib import Path
import platform
import signal
import statistics
import subprocess
import tempfile
import threading
import time


def execute(command, timeout, capture):
    with tempfile.TemporaryFile() as stdout, tempfile.TemporaryFile() as stderr, tempfile.NamedTemporaryFile() as metrics:
        started = time.perf_counter()
        wrapped = ["/usr/bin/time", "--format=%U %S %M", "--output", metrics.name, *command]
        process = subprocess.Popen(wrapped, stdout=stdout if capture else subprocess.DEVNULL,
                                   stderr=stderr, start_new_session=True)
        expired = threading.Event()
        def kill():
            expired.set()
            try:
                os.killpg(process.pid, signal.SIGKILL)
            except ProcessLookupError:
                pass
        watchdog = threading.Timer(timeout, kill)
        watchdog.daemon = True
        watchdog.start()
        try:
            _, status, _usage = os.wait4(process.pid, 0)
        finally:
            watchdog.cancel()
        elapsed = time.perf_counter()-started
        process.returncode = os.waitstatus_to_exitcode(status)
        stderr.seek(0)
        stdout.seek(0)
        diagnostic = stderr.read().decode(errors="replace")
        metrics.seek(0)
        metric_lines = metrics.read().decode().splitlines()
        parts = metric_lines[-1].split() if metric_lines else []
        if len(parts) == 3:
            user_seconds, system_seconds, max_rss_kib = float(parts[0]), float(parts[1]), int(parts[2])
        else:
            user_seconds = system_seconds = max_rss_kib = None
            if process.returncode == 0:
                raise RuntimeError("GNU time did not produce valid child CPU/RSS metrics")
        return {"exit_code": process.returncode, "timed_out": expired.is_set(),
                "stdout": stdout.read().decode() if capture else "", "stderr": diagnostic,
                "seconds": elapsed, "user_seconds": user_seconds, "system_seconds": system_seconds,
                "max_rss_kib": max_rss_kib, "stderr_bytes": len(diagnostic.encode())}


def run(command, timeout):
    return execute(command, timeout, True)


def normalized(value):
    return {language: {**details, "files": sorted(details.get("files", []))}
            for language, details in value.items()}


def measured(command, timeout):
    result = execute(command, timeout, False)
    if result["exit_code"] or result["timed_out"]:
        raise RuntimeError(f"timing failed exit={result['exit_code']} timeout={result['timed_out']}: {result['stderr'][:2000]}")
    return {key: result[key] for key in ["seconds", "user_seconds", "system_seconds", "max_rss_kib", "stderr_bytes"]}


def summary(samples):
    values = sorted(sample["seconds"] for sample in samples)
    return {"runs": len(samples), "median_seconds": statistics.median(values),
            "p95_seconds": values[math.ceil(.95*len(values))-1], "max_seconds": max(values),
            "min_seconds": min(values), "peak_rss_kib": max(sample["max_rss_kib"] for sample in samples),
            "coefficient_of_variation": statistics.pstdev(values)/statistics.mean(values)}


def verify_inputs(root, fixture, variant, verified):
    files = {file["path"]: file for file in variant["files"]}
    repo, flat = root / fixture["git"], root / variant["flat"]
    if (flat / ".git").exists():
        raise RuntimeError(f"flat input has Git metadata: {flat}")
    current = {path.relative_to(flat).as_posix() for path in flat.rglob("*") if path.is_file()}
    if current != set(files):
        raise RuntimeError(f"flat file list differs from generated manifest: {flat}")
    tree = subprocess.check_output(["git", "-C", str(repo), "ls-tree", "-r", "-z", variant["revision"]])
    git_files = {}
    for entry in tree.split(b"\0"):
        if not entry:
            continue
        metadata, name = entry.split(b"\t", 1)
        mode, kind, oid = metadata.decode().split()
        if mode not in ("100644", "100755") or kind != "blob":
            raise RuntimeError("stress generator produced unexpected nonregular Git entry")
        git_files[name.decode()] = oid
    if git_files != {name: item["git_blob_oid"] for name, item in files.items()}:
        raise RuntimeError("committed Git blob hashes differ from generated bytes")
    for name, item in files.items():
        path = flat / name
        info = path.stat()
        key = (info.st_dev, info.st_ino, info.st_size, info.st_mtime_ns)
        if key not in verified:
            digest = hashlib.sha256()
            with path.open("rb") as stream:
                for block in iter(lambda: stream.read(1024*1024), b""):
                    digest.update(block)
            verified[key] = digest.hexdigest()
        if info.st_size != item["bytes"] or verified[key] != item["sha256"]:
            raise RuntimeError(f"flat input size or SHA-256 differs: {name}")
    return files


def assert_accounting(value, files, assertions):
    paths = {}
    for language, details in value.items():
        counted = details.get("files", [])
        if any(path not in files for path in counted):
            raise AssertionError("oracle returned path outside manifest")
        if details["size"] != sum(files[path]["bytes"] for path in counted):
            raise AssertionError(f"{language}: full byte accounting failed")
        for path in counted:
            if path in paths:
                raise AssertionError(f"file counted in multiple languages: {path}")
            paths[path] = language
    for expected in assertions:
        if paths.get(expected["path"]) != expected["language"]:
            raise AssertionError(f"fixture expectation failed: {expected}; actual {paths.get(expected['path'])}")
        if "bytes" in expected and files[expected["path"]]["bytes"] != expected["bytes"]:
            raise AssertionError("fixture byte expectation failed")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--fixtures", type=Path, default=Path("/stress"))
    parser.add_argument("--candidate", type=Path, default=Path("/candidate/dircue"))
    parser.add_argument("--output", type=Path, default=Path("/results/stress.json"))
    parser.add_argument("--scenario", action="append", default=[])
    parser.add_argument("--build-receipt", type=Path)
    parser.add_argument("--runs", type=int, default=20)
    parser.add_argument("--warmup", type=int, default=3)
    parser.add_argument("--timeout", type=int, default=1800)
    args = parser.parse_args()
    if args.runs < 0 or args.warmup < 0 or args.timeout <= 0:
        parser.error("runs/warmup must be nonnegative; timeout must be positive")
    if platform.system() != "Linux":
        parser.error("run inside the pinned Linux reference container (wait4 RSS units)")
    manifest_path = args.fixtures / "manifest.json"
    manifest = json.loads(manifest_path.read_text())
    if "finished_at_utc" not in manifest:
        parser.error("fixture generation is incomplete")
    fixtures = [f for f in manifest["fixtures"] if not args.scenario or f["name"] in args.scenario]
    if not fixtures or set(args.scenario)-{f["name"] for f in fixtures}:
        parser.error("requested scenarios missing from fixture manifest")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    artifacts = args.output.parent / (args.output.stem+"-details")
    artifacts.mkdir(exist_ok=True)
    def optional(name):
        path = Path(name)
        return path.read_text() if path.exists() else None
    report = {"schema_version": "1.0.0", "started_at_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
              "profile": manifest["profile"], "fixture_parameters": manifest["parameters"], "fixture_manifest_sha256": hashlib.sha256(manifest_path.read_bytes()).hexdigest(),
              "fixture_generator_sha256": manifest["generator_sha256"], "packed_views": manifest.get("packed_views"),
              "harness_sha256": hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
              "candidate_sha256": hashlib.sha256(args.candidate.read_bytes()).hexdigest(),
              "candidate_version": run([str(args.candidate), "--version"], args.timeout),
              "reference_version": run(["github-linguist", "--version"], args.timeout),
              "environment": {"platform": platform.platform(), "cpu_count": os.cpu_count(),
                              "memory_max": optional("/sys/fs/cgroup/memory.max"), "cpu_max": optional("/sys/fs/cgroup/cpu.max"),
                              "meminfo": optional("/proc/meminfo"), "mounts": optional("/proc/mounts"),
                              "gems": optional("/reference-gems.txt")},
              "fixture_storage": {key: manifest[key] for key in ["unique_allocated_bytes", "disk_free_before", "disk_free_after"]},
              "methodology": {"runs": args.runs, "warmup": args.warmup, "cache": "warm, no cache flush",
                              "order": "rotated tool order each iteration", "timing": "perf_counter around GNU time spawn/wait4; GNU time reports target-child CPU and Linux peak RSS, excluding Python pre-exec fork high-water mark",
                              "correctness": "exact names, percentage strings, full byte totals and file sets against actual Ruby, plus full source hash verification",
                              "flat_oracle": "Ruby committed tree with identical blob content and root attributes; no Ruby flat-directory support assumed",
                              "size_caveat": "source bytes are fully written and hashed before scanning; profilers may read only classification prefixes. Logical bytes per second is not physical disk throughput.",
                              "tail_caveat": "20 samples cannot establish rare-tail latency"},
              "cases": []}
    if report["reference_version"]["exit_code"] or report["reference_version"]["stdout"].strip() != "github-linguist 9.7.0":
        parser.error("reference must be pinned github-linguist 9.7.0")
    if args.build_receipt:
        receipt = json.loads(args.build_receipt.read_text())
        if receipt["candidate_sha256"] != report["candidate_sha256"]:
            parser.error("candidate SHA does not match build receipt")
        report["build_receipt"] = receipt
    verified = {}
    failed = False
    for fixture in fixtures:
        for variant in fixture["variants"]:
            files = verify_inputs(args.fixtures, fixture, variant, verified)
            limits = [None] + fixture.get("tree_size_limits", [])
            for limit in limits:
                name = fixture["name"]+"-"+variant["name"]+(f"-limit{limit}" if limit is not None else "")
                flags = ["--json", "--breakdown"] + ([f"--tree-size={limit}"] if limit is not None else [])
                git_path, flat_path = str(args.fixtures/fixture["git"]), str(args.fixtures/variant["flat"])
                commands = {"linguist_git": ["github-linguist", *flags, "--rev", variant["revision"], git_path],
                            "auragaze_git": [str(args.candidate), *flags, "--rev", variant["revision"], git_path],
                            "auragaze_flat": [str(args.candidate), *flags, flat_path]}
                item = {"name": name, "fixture": fixture["name"], "revision": variant["revision"],
                        "logical_source_bytes": variant["logical_bytes"], "source_files": variant["file_count"],
                        "allocated_source_bytes": variant["allocated_source_bytes"], "git_storage": fixture["git_storage"],
                        "packed_history": fixture.get("packed_history"), "packed_backend": fixture.get("packed_backend"), "commands": commands, "results": {}, "match": False}
                try:
                    parsed = {}
                    for tool, command in commands.items():
                        result = run(command, args.timeout)
                        artifact = artifacts / f"{name}-{tool}.json"
                        artifact.write_text(json.dumps(result, indent=2)+"\n")
                        item["results"][tool] = {"exit_code": result["exit_code"], "stderr": result["stderr"],
                                                 "seconds": result["seconds"], "max_rss_kib": result["max_rss_kib"],
                                                 "artifact": str(artifact.name), "sha256": hashlib.sha256(artifact.read_bytes()).hexdigest()}
                        if result["exit_code"]:
                            raise RuntimeError(f"{tool} exited {result['exit_code']}: {result['stderr'][:1000]}")
                        parsed[tool] = normalized(json.loads(result["stdout"]))
                    expected = parsed["linguist_git"]
                    assert_accounting(expected, files, variant["assertions"] if limit is None else [])
                    if fixture["name"] == "tree-count":
                        effective_limit = limit if limit is not None else 100000
                        if (expected == {}) != (variant["file_count"] >= effective_limit):
                            raise AssertionError("oracle tree-size boundary differs from fixture expectation")
                    item["match"] = all(value == expected for value in parsed.values())
                    item["language_bytes"] = sum(value["size"] for value in expected.values())
                    item["counted_files"] = sum(len(value["files"]) for value in expected.values())
                    if not item["match"]:
                        item["error"] = "candidate language JSON differs; inspect retained outputs"
                    # Modern detector observations are exercised at scale without treating
                    # their heuristic results as a dependency graph or vulnerability claim.
                    if item["match"] and limit is None and fixture["name"] in ("etl-pipeline", "dotnet-graph"):
                        item["extended"] = {}
                        for source, path, extra in [("git", git_path, ["--rev", variant["revision"]]), ("flat", flat_path, [])]:
                            extended = run([str(args.candidate), "analyze", "all", "--json", "--breakdown", *extra, path], args.timeout)
                            artifact = artifacts / f"{name}-all-{source}.json"
                            artifact.write_text(json.dumps(extended, indent=2)+"\n")
                            if extended["exit_code"]:
                                raise RuntimeError(f"analyze all {source} failed: {extended['stderr'][:1000]}")
                            data = json.loads(extended["stdout"])
                            actual_languages = {language["name"]: {"size": language["bytes"], "files": sorted(language.get("files", []))} for language in data["languages"]}
                            expected_languages = {language: {"size": details["size"], "files": details["files"]} for language, details in expected.items()}
                            if actual_languages != expected_languages:
                                raise AssertionError("analyze all languages differ from Ruby oracle")
                            ecosystem = "maven" if fixture["name"] == "etl-pipeline" else "nuget"
                            if not any(finding["name"] == ecosystem for finding in data["ecosystems"]):
                                raise AssertionError(f"expected {ecosystem} observation missing")
                            item["extended"][source] = {"artifact": artifact.name,
                                                        "ecosystem_findings": len(data["ecosystems"]),
                                                        "layout_findings": len(data["layouts"]), "warnings": data["warnings"]}
                    if item["match"] and args.runs:
                        for _ in range(args.warmup):
                            for command in commands.values():
                                measured(command, args.timeout)
                        samples = {tool: [] for tool in commands}
                        order = list(commands)
                        for iteration in range(args.runs):
                            offset = iteration % len(order)
                            for tool in order[offset:]+order[:offset]:
                                samples[tool].append(measured(commands[tool], args.timeout))
                        item["samples"] = samples
                        item["timings"] = {tool: summary(values) for tool, values in samples.items()}
                        item["git_median_speedup"] = item["timings"]["linguist_git"]["median_seconds"]/item["timings"]["auragaze_git"]["median_seconds"]
                        item["flat_median_ratio_to_git_reference"] = item["timings"]["linguist_git"]["median_seconds"]/item["timings"]["auragaze_flat"]["median_seconds"]
                except (RuntimeError, AssertionError, subprocess.TimeoutExpired, ValueError) as error:
                    item["error"] = str(error)
                    item["match"] = False
                failed |= not item["match"]
                report["cases"].append(item)
                args.output.write_text(json.dumps(report, indent=2)+"\n")
                print(json.dumps({"case": name, "match": item["match"], "error": item.get("error"), "git_speedup": item.get("git_median_speedup")}), flush=True)
    report["candidate_sha256_after"] = hashlib.sha256(args.candidate.read_bytes()).hexdigest()
    if report["candidate_sha256_after"] != report["candidate_sha256"]:
        failed = True
        report["error"] = "candidate binary changed during the run"
    report["passed"] = not failed
    report["performance_passed"] = (all(item.get("git_median_speedup", 0) >= 1 for item in report["cases"]) if args.runs and not failed else None)
    report["finished_at_utc"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    args.output.write_text(json.dumps(report, indent=2)+"\n")
    raise SystemExit(0 if not failed and report["performance_passed"] is not False else 1)

if __name__ == "__main__":
    main()
