#!/usr/bin/env python3
"""Compare existing 0.2 CLI stdout, stderr, and exit codes against a candidate."""
import argparse
import datetime
import hashlib
import json
import os
from pathlib import Path
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[2]
EXPECTED_V020_SHA256 = '62c884a82eacb8153cc57c6c3cc980ec1fba35391b02ab1690e5e850a145d059'


def sha(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def source_provenance():
    def git(*args):
        result = subprocess.run(['git', '-c', 'safe.directory='+str(ROOT), *args], cwd=ROOT, capture_output=True, check=True)
        return result.stdout
    files = git('ls-files', '--cached', '--others', '--exclude-standard', '-z').decode().split('\0')
    # Hash build inputs rather than result files, which would make the receipt
    # self-referential. Paths are included to distinguish moved source files.
    files = sorted({name for name in files if name and (
        name.endswith(('.go', '.mod', '.sum')) or name == 'internal/cli/mimedata/ext_mime.db')
        and not name.startswith('prototypes/')})
    digest = hashlib.sha256()
    for name in files:
        path = ROOT/name
        if path.is_file():
            digest.update(name.encode()+b'\0'+bytes.fromhex(sha(path)))
    return {'commit': git('rev-parse', 'HEAD').decode().strip(),
            'status': git('status', '--short').decode(),
            'build_inputs_sha256': digest.hexdigest(), 'build_input_files': len(files),
            'build_input_rule': '*.go, *.mod, *.sum and embedded MIME database; prototypes excluded; path plus SHA-256 bytes in lexical order'}


def execute(binary, args, cwd, env):
    result = subprocess.run([str(binary), *args], cwd=cwd, env=env, capture_output=True, timeout=60)
    return {'exit': result.returncode, 'stdout': result.stdout.decode('utf-8', errors='backslashreplace'),
            'stderr': result.stderr.decode('utf-8', errors='backslashreplace')}


def fixture(base):
    env = os.environ | {'GIT_CONFIG_NOSYSTEM': '1', 'GIT_CONFIG_GLOBAL': os.devnull,
        'GIT_AUTHOR_NAME': 'Compatibility Fixture', 'GIT_AUTHOR_EMAIL': 'compat@example.invalid',
        'GIT_COMMITTER_NAME': 'Compatibility Fixture', 'GIT_COMMITTER_EMAIL': 'compat@example.invalid',
        'GIT_AUTHOR_DATE': '2026-01-01T00:00:00+00:00', 'GIT_COMMITTER_DATE': '2026-01-01T00:00:00+00:00'}
    files = {'Main.cs': '// header\nclass Main {}\n', 'Main.java': 'class Main {}\n',
        'a.py': 'print(1)\n', 'go.mod': 'module example\n\ngo 1.26\n',
        'package.json': '{"dependencies":{"react":"19"}}\n',
        'pom.xml': '<project><artifactId>example</artifactId></project>\n',
        'Example.csproj': '<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0</TargetFramework></PropertyGroup></Project>\n',
        'log.xml': '<log/>\n', 'README.md': '# Fixture\n', 'data.bin': '\x00x',
        'generated/generated.g.cs': '// <auto-generated>\nclass G {}\n',
        'vendor/Vendor.java': 'class V {}\n', 'nested/Override.java': 'class Override {}\n',
        'nested/.gitattributes': 'Override.java linguist-language=C#\n',
        '.gitattributes': '*.xml linguist-detectable=true\ngenerated/** linguist-generated\nvendor/** linguist-vendored\n',
        'long.java': 'class Long {/*\n' + 'comment\n'*20000 + '*/}\n'}
    flat, repo, empty, nohead = [base/name for name in ('flat', 'repo', 'empty', 'nohead')]
    for folder in (flat, repo, empty, nohead):
        folder.mkdir()
    for folder in (flat, repo):
        for name, content in files.items():
            path = folder/name
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    def git(cwd, *args):
        subprocess.run(['git', '-c', 'core.hooksPath=/dev/null', '-c', 'commit.gpgsign=false', *args],
            cwd=cwd, env=env, check=True, capture_output=True)
    git(repo, 'init', '-q', '-b', 'main')
    git(repo, 'add', '.')
    git(repo, 'commit', '-qm', 'base')
    (repo/'Main.java').write_text('class Changed { int x; }\n')
    git(repo, 'add', '.')
    git(repo, 'commit', '-qm', 'second')
    (repo/'Main.cs').write_text('class Dirty {}\n')
    git(repo, 'add', 'Main.cs')
    (repo/'Main.java').write_text('class Unstaged {}\n')
    (repo/'untracked.py').write_text('print(2)\n')
    git(nohead, 'init', '-q', '-b', 'main')
    (nohead/'Main.java').write_text('class Main {}\n')
    for name in ('analyze', 'metrics', '-folder'):
        folder = flat/name
        folder.mkdir()
        (folder/'a.java').write_text('class A {}\n')
    cases = []
    options = [[], ['--json'], ['-bj'], ['--breakdown'], ['--strategies'],
        ['analyze', 'languages', '--json'], ['analyze', 'all', '--json'], ['analyze', 'all'],
        ['analyze', 'ecosystems', '--json'], ['analyze', 'frameworks', '--json'],
        ['--source', 'directory', '--json'], ['--tree-size', '1', '--json'],
        ['--max-file-bytes', '10', '--json'], ['--workers', '1', '--json'],
        ['analyze', 'metrics', '--json'], ['analyze', 'metrics', '--json', '--files'],
        ['analyze', 'metrics', '--json', '--metrics-scope', 'text'],
        ['analyze', 'metrics', '--json', '--metrics-max-file-bytes', '1024'],
        ['analyze', 'all', '--json', '--metrics'], ['analyze', 'all', '--json', '--metrics', '--files']]
    for folder in (flat, repo, empty, nohead):
        cases.extend((folder, args) for args in options)
    for args in [['--rev', 'HEAD~1', '--json'], ['--source', 'git', '--json'],
        ['--source', 'git', '--rev', 'not-a-revision', '--json'], ['--json', 'Main.cs'],
        ['Main.java'], ['-bjs', 'Main.java'], ['--source', 'directory', '--json', 'Main.cs'],
        ['analyze', 'languages', '--json', 'Main.cs'],
        ['analyze', 'metrics', '--json', '--rev', 'HEAD~1'],
        ['analyze', 'all', '--metrics', '--json', '--source', 'directory'],
        ['analyze', 'metrics', '--json', '--source', 'directory']]:
        cases.append((repo, args))
    for args in [['--json', 'missing'], ['--source', 'bad', '--json'], ['--workers', '-1'],
        ['--workers', '1025'], ['--max-file-bytes', '-1'], ['--tree-size', '0', '--json'],
        ['--tree-size', '-1', '--json'], ['--unknown'], ['--source'], ['--workers', 'no'],
        ['--rev', 'HEAD'], ['--source', 'git', '--json'], ['--source', 'directory', '--rev', 'HEAD'],
        ['--json', 'Main.java'], ['analyze', 'all', 'Main.java'], ['analyze', 'languages', 'Main.java'],
        ['--json', '--', 'Main.java'], ['--json', 'Main.java', 'a.py'], ['-j', 'false'],
        ['analyze', 'metrics', '--metrics-scope', 'bad'],
        ['analyze', 'metrics', '--metrics-max-file-bytes', '-1'],
        ['analyze', 'metrics', '--metrics-max-file-bytes', '268435457'],
        ['analyze', 'all', '--metrics-scope', 'bad'],
        ['analyze', 'metrics', '--json', 'Main.java']]:
        cases.append((flat, args))
    cases.extend((flat, ['--json', '--', name]) for name in ('analyze', 'metrics', '-folder'))
    return env, flat, cases


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--baseline', type=Path, required=True)
    parser.add_argument('--candidate', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    baseline, candidate = args.baseline.resolve(), args.candidate.resolve()
    if sha(baseline) != EXPECTED_V020_SHA256:
        parser.error('baseline is not the verified native v0.2.0 release binary')
    report = {'schema_version': '1.0.0', 'started_at_utc': datetime.datetime.now(datetime.timezone.utc).isoformat(),
        'baseline': {'path': str(baseline), 'sha256': sha(baseline), 'release': 'v0.2.0'},
        'candidate': {'path': str(candidate), 'sha256': sha(candidate)},
        'source': source_provenance(), 'harness_sha256': sha(__file__), 'cases': [], 'interface_additions': []}
    with tempfile.TemporaryDirectory(prefix='dircue-v030-compat-') as folder:
        base = Path(folder)
        env, flat, cases = fixture(base)
        for cwd, options in cases:
            old, new = [execute(binary, options, cwd, env) for binary in (baseline, candidate)]
            report['cases'].append({'cwd': str(cwd.relative_to(base)), 'args': options, 'equal': old == new,
                'baseline': old, 'candidate': new})
        for options in [['--version'], ['--help'], ['analyze'], ['analyze', '--help'],
            ['analyze', 'all', '--help']]:
            report['interface_additions'].append({'args': options,
                'baseline': execute(baseline, options, flat, env), 'candidate': execute(candidate, options, flat, env)})
    report['exact_matches'] = sum(row['equal'] for row in report['cases'])
    report['total'] = len(report['cases'])
    report['passed'] = report['exact_matches'] == report['total']
    report['finished_at_utc'] = datetime.datetime.now(datetime.timezone.utc).isoformat()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(report, indent=2)+'\n')
    print(json.dumps({'passed': report['passed'], 'exact_matches': report['exact_matches'], 'total': report['total'],
        'differences': [{'cwd': row['cwd'], 'args': row['args']} for row in report['cases'] if not row['equal']]}))
    raise SystemExit(0 if report['passed'] else 1)


if __name__ == '__main__':
    main()
