// Package codemetrics counts source lines using pinned scc grammars.
package codemetrics

// grammarNames maps ungrouped Linguist names to scc 4.1.0 grammars.
// Additions are explicit so upstream name changes cannot silently alter coverage.
var grammarNames = map[string]string{
	"ABAP":                "ABAP",
	"ABNF":                "ABNF",
	"AL":                  "AL",
	"APL":                 "APL",
	"ASP.NET":             "ASP.NET",
	"ATS":                 "ATS",
	"ActionScript":        "ActionScript",
	"Ada":                 "Ada",
	"Agda":                "Agda",
	"Alloy":               "Alloy",
	"Apex":                "Apex",
	"AppleScript":         "AppleScript",
	"AsciiDoc":            "AsciiDoc",
	"Assembly":            "Assembly",
	"Astro":               "Astro",
	"Bicep":               "Bicep",
	"Blueprint":           "Blueprint",
	"Boo":                 "Boo",
	"Brainfuck":           "Brainfuck",
	"Bru":                 "Bru",
	"BuildStream":         "BuildStream",
	"C":                   "C",
	"C#":                  "C#",
	"C++":                 "C++",
	"C3":                  "C3",
	"CMake":               "CMake",
	"COBOL":               "COBOL",
	"CSS":                 "CSS",
	"CSV":                 "CSV",
	"Cairo":               "Cairo",
	"Cangjie":             "Cangjie",
	"Cap'n Proto":         "Cap'n Proto",
	"Ceylon":              "Ceylon",
	"Chapel":              "Chapel",
	"Circom":              "Circom",
	"Clojure":             "Clojure",
	"CodeQL":              "CodeQL",
	"CoffeeScript":        "CoffeeScript",
	"ColdFusion":          "ColdFusion",
	"Common Lisp":         "Lisp",
	"Creole":              "Creole",
	"Crystal":             "Crystal",
	"Cuda":                "Cuda",
	"Cypher":              "Cypher",
	"Cython":              "Cython",
	"D":                   "D",
	"D2":                  "D2",
	"DM":                  "DM",
	"Dart":                "Dart",
	"Dhall":               "Dhall",
	"Dockerfile":          "Dockerfile",
	"Elixir":              "Elixir",
	"Elm":                 "Elm",
	"Emacs Lisp":          "Emacs Lisp",
	"Erlang":              "Erlang",
	"F#":                  "F#",
	"F*":                  "F*",
	"Factor":              "Factor",
	"Fennel":              "Fennel",
	"Forth":               "Forth",
	"Fortran":             "FORTRAN Legacy",
	"Fortran Free Form":   "Fortran Modern",
	"Futhark":             "Futhark",
	"GDScript":            "GDScript",
	"GLSL":                "GLSL",
	"GN":                  "GN",
	"Game Maker Language": "Game Maker Language",
	"Gherkin":             "Gherkin Specification",
	"Gleam":               "Gleam",
	"Go":                  "Go",
	"Go Template":         "Go Template",
	"Gradle":              "Gradle",
	"GraphQL":             "GraphQL",
	"Groovy":              "Groovy",
	"HCL":                 "HCL",
	"HTML":                "HTML",
	"HTML+ERB":            "Ruby HTML",
	"HTML+Razor":          "Razor",
	"Haml":                "HAML",
	"Handlebars":          "Handlebars",
	"Hare":                "Hare",
	"Haskell":             "Haskell",
	"Haxe":                "Haxe",
	"IDL":                 "IDL",
	"INI":                 "INI",
	"Idris":               "Idris",
	"Isabelle":            "Isabelle",
	"JCL":                 "JCL",
	"JSON":                "JSON",
	"JSON5":               "JSON5",
	"Janet":               "Janet",
	"Java":                "Java",
	"JavaScript":          "JavaScript",
	"Jinja":               "Jinja",
	"Jsonnet":             "Jsonnet",
	"Julia":               "Julia",
	"Just":                "Just",
	"Kotlin":              "Kotlin",
	"LOLCODE":             "LOLCODE",
	"Lean":                "Lean",
	"Less":                "LESS",
	"LiveScript":          "LiveScript",
	"Lua":                 "Lua",
	"Luau":                "Luau",
	"MATLAB":              "MATLAB",
	"MDX":                 "MDX",
	"MLIR":                "MLIR",
	"MQL4":                "MQL4",
	"MQL5":                "MQL5",
	"Makefile":            "Makefile",
	"Mako":                "Mako",
	"Markdown":            "Markdown",
	"Max":                 "Max",
	"Meson":               "Meson",
	"Metal":               "Metal",
	"Mojo":                "Mojo",
	"Monkey C":            "Monkey C",
	"Move":                "Move",
	"Mustache":            "Mustache",
	"Nim":                 "Nim",
	"Nix":                 "Nix",
	"Nushell":             "Nushell",
	"OCaml":               "OCaml",
	"Objective-C":         "Objective C",
	"Objective-C++":       "Objective C++",
	"Odin":                "Odin",
	"OpenQASM":            "OpenQASM",
	"Org":                 "Org",
	"Oz":                  "Oz",
	"PHP":                 "PHP",
	"Pascal":              "Pascal",
	"Perl":                "Perl",
	"Pkl":                 "Pkl",
	"Pony":                "Pony",
	"PostScript":          "PostScript",
	"PowerShell":          "Powershell",
	"Processing":          "Processing",
	"Prolog":              "Prolog",
	"Protocol Buffer":     "Protocol Buffers",
	"Puppet":              "Puppet",
	"PureScript":          "PureScript",
	"Python":              "Python",
	"Q#":                  "Q#",
	"QML":                 "QML",
	"R":                   "R",
	"RAML":                "RAML",
	"Racket":              "Racket",
	"Raku":                "Raku",
	"ReScript":            "ReScript",
	"Rebol":               "Rebol",
	"Redscript":           "Redscript",
	"Rich Text Format":    "Rich Text Format",
	"Ruby":                "Ruby",
	"Rust":                "Rust",
	"SAS":                 "SAS",
	"SQL":                 "SQL",
	"SRecode Template":    "SRecode Template",
	"SVG":                 "SVG",
	"Sass":                "Sass",
	"Scala":               "Scala",
	"Scheme":              "Scheme",
	"Shell":               "Shell",
	"Sieve":               "Sieve",
	"Slang":               "Slang",
	"Slint":               "Slint",
	"Smalltalk":           "Smalltalk",
	"Smarty":              "Smarty Template",
	"Snakemake":           "Snakemake",
	"Solidity":            "Solidity",
	"Stan":                "Stan",
	"Standard ML":         "Standard ML (SML)",
	"Stata":               "Stata",
	"Stylus":              "Stylus",
	"Svelte":              "Svelte",
	"Swift":               "Swift",
	"SystemVerilog":       "SystemVerilog",
	"TOML":                "TOML",
	"TSX":                 "TypeScript",
	"Tact":                "Tact",
	"Tcl":                 "TCL",
	"TeX":                 "TeX",
	"Teal":                "Teal",
	"Text":                "Plain Text",
	"Textile":             "Textile",
	"Thrift":              "Thrift",
	"TypeScript":          "TypeScript",
	"TypeSpec":            "TypeSpec",
	"Typst":               "Typst",
	"V":                   "V",
	"VHDL":                "VHDL",
	"Vala":                "Vala",
	"Verilog":             "Verilog",
	"Visual Basic .NET":   "Visual Basic",
	"Vue":                 "Vue",
	"Wren":                "Wren",
	"XML":                 "XML",
	"XSLT":                "Extensible Stylesheet Language Transformations",
	"Xtend":               "Xtend",
	"YAML":                "YAML",
	"Zig":                 "Zig",
	"hoon":                "hoon",
	"jq":                  "jq",
	"reStructuredText":    "ReStructuredText",
	"sed":                 "sed",
}

// Grammar resolves a previously identified language without extension-based guessing.
// filename is reserved for grammars that distinguish file roles within a language.
func Grammar(filename, linguistLanguage string) (string, bool) {
	grammar, ok := grammarNames[linguistLanguage]
	return grammar, ok
}
