package scanner

import (
	"context"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/war-and-code/dircue/pkg/profile"
)

func metricsFiles(t *testing.T, report *profile.Report) map[string]profile.FileMetrics {
	t.Helper()
	if report.Metrics == nil || report.Metrics.Files == nil {
		t.Fatal("missing metrics file detail")
	}
	files := make(map[string]profile.FileMetrics)
	for _, file := range *report.Metrics.Files {
		files[file.Path] = file
	}
	return files
}

func TestMetricsFullContentAndSourceIdentity(t *testing.T) {
	// Comment state crosses both the language classifier prefix and the hook
	// prefix. Counting independent prefixes or chunks produces different totals.
	content := "package main\n/*\n" + strings.Repeat("inside the comment\n", 70000) + "*/\nfunc main() {}\n"
	root, repo, revision := gitFixture(t, map[string]string{"src/main.go": content})
	for _, source := range []string{"directory", "git"} {
		opts := Options{Source: source, Metrics: &MetricsOptions{IncludeFiles: true}}
		report, err := Scan(context.Background(), root, opts)
		if err != nil {
			t.Fatal(err)
		}
		file := metricsFiles(t, report)["src/main.go"]
		if file.Counts == nil || file.Counts.Lines != 70004 || file.Counts.Comment != 70002 || file.Counts.Code != 2 || file.Counts.Bytes != int64(len(content)) {
			t.Fatalf("full-file counts: %+v", file)
		}
		if report.Metrics.Status != "complete" || report.Metrics.Source != source {
			t.Fatalf("source: %+v", report.Metrics)
		}
		if source == "git" {
			commit, err := repo.CommitObject(revision)
			if err != nil {
				t.Fatal(err)
			}
			if report.Metrics.Tree != commit.TreeHash.String() {
				t.Fatal("wrong source tree")
			}
		}
		if err := os.WriteFile(filepath.Join(root, "src/main.go"), []byte("package dirty\n"), 0644); err != nil {
			t.Fatal(err)
		}
	}
}

func TestMetricsScopesAndLanguageInvariance(t *testing.T) {
	root := fixtures(t, map[string]string{
		"src/main.go": goSource, "src/sub/nested.go": goSource,
		"vendor/lib.go": goSource, "generated.go": "// Code generated by fixture. DO NOT EDIT.\n" + goSource,
		"README.md": "# title\n", "logs.xml": "<log>data</log>\n", "binary.go": "\x00binary",
	})
	base, err := Scan(context.Background(), root, Options{IncludeFiles: true})
	if err != nil {
		t.Fatal(err)
	}
	for _, scope := range []string{"source", "text"} {
		report, err := Scan(context.Background(), root, Options{IncludeFiles: true, Metrics: &MetricsOptions{Scope: scope, IncludeFiles: true}})
		if err != nil {
			t.Fatal(err)
		}
		if !reflect.DeepEqual(base.Languages, report.Languages) || base.Summary != report.Summary {
			t.Fatalf("metrics changed language report: %+v %+v", base, report)
		}
		files := metricsFiles(t, report)
		for _, filename := range []string{"vendor/lib.go", "generated.go", "README.md", "logs.xml"} {
			want := "skipped"
			if scope == "text" {
				want = "counted"
			}
			if files[filename].Status != want {
				t.Fatalf("%s %s: %+v", scope, filename, files[filename])
			}
		}
		if files["binary.go"].Reason != "binary" {
			t.Fatal("binary was not excluded")
		}
		if report.Metrics.Status != "complete" {
			t.Fatalf("expected exclusions made scope incomplete: %+v", report.Metrics)
		}
		for _, directory := range report.Metrics.Directories {
			if directory.Path == "src" && directory.Files != 1 {
				t.Fatal("directory totals include descendants")
			}
		}
	}
}

func TestMetricsOmissionsAndDeterministicAggregation(t *testing.T) {
	root := fixtures(t, map[string]string{
		"main.go": goSource, "large.go": strings.Repeat(goSource, 5000), "bad.go": "package test\n// \xff\n",
		"unmapped.aidl": "interface Example {}\n", ".gitattributes": "*.aidl linguist-language=AIDL\n",
	})
	var previous []byte
	for _, workers := range []int{1, 4, 16} {
		report, err := Scan(context.Background(), root, Options{Workers: workers, Metrics: &MetricsOptions{IncludeFiles: true, MaxFileBytes: 4096}})
		if err != nil {
			t.Fatal(err)
		}
		files := metricsFiles(t, report)
		for filename, reason := range map[string]string{"large.go": "file_too_large", "bad.go": "unsupported_encoding", "unmapped.aidl": "unsupported_language"} {
			if files[filename].Reason != reason {
				t.Fatalf("%s: %+v", filename, files[filename])
			}
			if files[filename].Counts != nil {
				t.Fatal("omitted file has invented counts")
			}
		}
		if report.Metrics.Status != "partial" || report.Metrics.Totals.Files != 1 {
			t.Fatalf("incomplete totals: %+v", report.Metrics)
		}
		encoded, err := json.Marshal(report.Metrics)
		if err != nil {
			t.Fatal(err)
		}
		if previous != nil && string(previous) != string(encoded) {
			t.Fatal("metrics depend on worker order")
		}
		previous = encoded
	}
}

func TestMetricsTreeLimitsAndOptions(t *testing.T) {
	root, _, _ := gitFixture(t, map[string]string{"main.go": goSource})
	for _, source := range []string{"git", "directory"} {
		report, err := Scan(context.Background(), root, Options{Source: source, MaxTreeSize: 1, Metrics: &MetricsOptions{IncludeFiles: true}})
		if err != nil {
			t.Fatal(err)
		}
		if report.Metrics.Status != "skipped" || report.Metrics.Totals.Files != 0 || report.Metrics.Files == nil || len(*report.Metrics.Files) != 0 {
			t.Fatalf("limit not disclosed: %+v", report.Metrics)
		}
	}
	for _, opts := range []MetricsOptions{{Scope: "invalid"}, {MaxFileBytes: -1}, {MaxFileBytes: MaxMetricsFileBytes + 1}} {
		if _, err := Scan(context.Background(), root, Options{Metrics: &opts}); err == nil {
			t.Fatal("invalid metric options accepted")
		}
	}
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	if _, err := Scan(ctx, root, Options{Metrics: &MetricsOptions{}}); !errors.Is(err, context.Canceled) {
		t.Fatalf("cancellation: %v", err)
	}
}

func TestMetricsChangedAndTruncatedSources(t *testing.T) {
	prefix := []byte("package main\n")
	for _, test := range []struct {
		name   string
		size   int64
		read   func(int64) ([]byte, int64, error)
		reason string
	}{
		{"truncated", 100, func(int64) ([]byte, int64, error) { return prefix, 100, nil }, "input_changed"},
		{"prefix changed", 100, func(int64) ([]byte, int64, error) { return []byte(strings.Repeat("x", 100)), 100, nil }, "input_changed"},
		{"grown", 100, func(int64) ([]byte, int64, error) { return nil, 1000, nil }, "file_too_large"},
	} {
		t.Run(test.name, func(t *testing.T) {
			item := job{path: "main.go", size: test.size, read: test.read}
			value := result{metrics: &profile.FileMetrics{Path: item.path, Status: "skipped"}}
			err := countFileMetrics(context.Background(), nil, item, Options{Metrics: &MetricsOptions{Scope: "source", MaxFileBytes: 200}}, &value, "Go", prefix, test.size, true)
			if err != nil || value.metrics.Reason != test.reason || value.metrics.Counts != nil {
				t.Fatalf("%v %+v", err, value.metrics)
			}
		})
	}
}
