package scanner

import (
	"context"
	"encoding/binary"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"runtime"
	"strings"
	"testing"

	"dircue/pkg/profile"
	git "github.com/go-git/go-git/v5"
)

const goSource = "package main\n\nfunc main() {}\n"

func fixtures(t testing.TB, files map[string]string) string {
	t.Helper()
	root := t.TempDir()
	for filename, content := range files {
		filename = filepath.Join(root, filepath.FromSlash(filename))
		if err := os.MkdirAll(filepath.Dir(filename), 0755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filename, []byte(content), 0644); err != nil {
			t.Fatal(err)
		}
	}
	return root
}

type detectorFunc func(context.Context, profile.File) ([]profile.Finding, error)

func (f detectorFunc) Name() string { return "test" }
func (f detectorFunc) Detect(ctx context.Context, file profile.File) ([]profile.Finding, error) {
	return f(ctx, file)
}

func observingDetector(_ context.Context, file profile.File) ([]profile.Finding, error) {
	return []profile.Finding{{Kind: "ecosystem", Name: "observed", Root: ".", Evidence: []string{file.Path}}}, nil
}

func TestRecoverableReadPreservesInventoryAndProtocolErrorsRemainFatal(t *testing.T) {
	secret := errors.New("open /private/host/secret: permission denied")
	item := job{path: "app.csproj", size: 42, read: func(int64) ([]byte, int64, error) {
		return nil, 0, secret
	}}
	value, err := analyzeSelectedFile(context.Background(), nil, item, Options{Projects: true, Discovery: true})
	if !isRecoverableFileError(err) || value.path != item.path || !value.inventoried || value.discoveryFile == nil {
		t.Fatalf("read failure lost retained metadata: value=%+v err=%v", value, err)
	}
	protocol := errors.New("structural worker protocol mismatch")
	if isRecoverableFileError(protocol) {
		t.Fatal("worker protocol failure classified as recoverable file I/O")
	}
	registryItem := item
	registryItem.path = ".npmrc"
	registryValue, registryErr := analyzeSelectedFile(context.Background(), nil, registryItem, Options{Registries: true})
	if !isRecoverableFileError(registryErr) || strings.Contains(registryErr.Error(), "private") || registryValue.registryFile == nil {
		t.Fatalf("registry read error was not sanitized with metadata preserved: value=%+v err=%v", registryValue, registryErr)
	}
}

func TestScanWithoutGitAndExclusions(t *testing.T) {
	root := fixtures(t, map[string]string{
		"main.go":                  goSource,
		"script.py":                "print('hello')\n",
		"data.json":                "{}",
		".hidden.go":               goSource,
		".github/workflows/ci.yml": "name: CI\n",
		"go.mod":                   "module example\n",
		"package-lock.json":        "{}",
		"generated.go":             "// Code generated by test. DO NOT EDIT.\n" + goSource,
		"vendor/example/lib.go":    goSource,
		"image.go":                 "\x00\x01binary",
		".git/ignored.go":          goSource,
	})
	report, err := Scan(context.Background(), root, Options{IncludeFiles: true, Detectors: []profile.Detector{detectorFunc(observingDetector)}})
	if err != nil {
		t.Fatal(err)
	}
	if report.Root != root || report.SchemaVersion != profile.SchemaVersion {
		t.Fatalf("wrong report metadata: %+v", report)
	}
	if len(report.Languages) != 2 {
		t.Fatalf("languages: %+v", report.Languages)
	}
	byLanguage := map[string]profile.Language{}
	for _, language := range report.Languages {
		byLanguage[language.Name] = language
	}
	if !reflect.DeepEqual(byLanguage["Go"].Files, []string{".hidden.go", "main.go"}) {
		t.Fatalf("Go files: %+v", byLanguage["Go"])
	}
	if byLanguage["Go"].Bytes != 2*int64(len(goSource)) {
		t.Fatalf("Go bytes: %+v", byLanguage["Go"])
	}
	if report.Summary.ScannedFiles != 10 || report.Summary.AnalyzedFiles != 8 || report.Summary.SkippedFiles != 2 {
		t.Fatalf("summary: %+v", report.Summary)
	}
	wantEvidence := []string{".github/workflows/ci.yml", ".hidden.go", "data.json", "generated.go", "go.mod", "main.go", "package-lock.json", "script.py"}
	if len(report.Ecosystems) != 1 || !reflect.DeepEqual(report.Ecosystems[0].Evidence, wantEvidence) {
		t.Fatalf("hook evidence: %+v", report.Ecosystems)
	}
}

func TestLateNULWithinClassificationPrefixIsBinary(t *testing.T) {
	plainRTF := strings.Repeat("{\\rtf1 text}", 700)
	rtf := plainRTF + "\x00"
	if !isBinaryContent([]byte(rtf)) {
		t.Fatal("NUL after Enry's 8,000-byte sniff was not detected")
	}
	csharp := "namespace Synthetic; public class Program {}\n" + strings.Repeat("// filler\n", 140_000)
	sizedCSharp := func(size, nulAt int) string {
		content := []byte(csharp[:size])
		if nulAt >= 0 {
			content[nulAt] = 0
		}
		return string(content)
	}
	lateNUL := sizedCSharp(300*1024, 200*1024)
	if !isBinaryContent([]byte(lateNUL)) {
		t.Fatal("binary detection did not inspect all supplied flat-file content")
	}
	if language, _ := DetectLanguage("late-nul.cs", []byte(lateNUL)); language != "" {
		t.Fatalf("complete flat-file content with a late NUL detected as %q", language)
	}
	beyondCharlockPrefix := sizedCSharp((1<<20)+1, 1<<20)
	if isBinaryContent([]byte(beyondCharlockPrefix)) {
		t.Fatal("binary detection read beyond Charlock Holmes' 1 MiB NUL scan")
	}
	for name, fixture := range map[string]struct {
		content string
		binary  bool
	}{
		"PostScript": {"%!PS-Adobe-\x00", false},
		"PNG":        {"\x89PNG\r\n\x1a\n", true},
		"GIF87a":     {"GIF87a", true},
		"GIF89a":     {"GIF89a", true},
		"PDF":        {"%PDF-", true},
		"JPEG":       {"\xff\xd8\xff", true},
		"UTF-32BE":   {"\x00\x00\xfe\xff\x00", false},
		"UTF-32LE":   {"\xff\xfe\x00\x00\x00", false},
		"UTF-16BE":   {"\xfe\xff\x00", false},
		"UTF-16LE":   {"\xff\xfe\x00", false},
	} {
		if got := isBinaryContent([]byte(fixture.content)); got != fixture.binary {
			t.Errorf("%s binary=%v, want %v", name, got, fixture.binary)
		}
	}
	utf16LE := func(nulAt int) string {
		units := (300*1024 - 2) / 2
		content := make([]byte, 2+units*2)
		content[0], content[1] = 0xff, 0xfe
		for i := range units {
			value := uint16(csharp[i])
			if i == nulAt {
				value = 0
			}
			binary.LittleEndian.PutUint16(content[2+i*2:], value)
		}
		return string(content)
	}
	utf16Within := utf16LE(5_000) // Past Enry's 8,000 raw-byte sniff, inside 128 KiB.
	utf16Beyond := utf16LE((200*1024 - 2) / 2)
	if language, strategy := DetectLanguage("within.cs", []byte(utf16Within)); language != "C#" || strategy != "Classifier" {
		t.Fatalf("BOM-marked UTF-16 with U+0000 detected as %q by %q", language, strategy)
	}
	if language, strategy := DetectLanguage("beyond.cs", []byte(utf16Beyond)); language != "C#" || strategy != "Classifier" {
		t.Fatalf("BOM-marked UTF-16 with a late U+0000 detected as %q by %q", language, strategy)
	}
	// ASP.NET Core's pinned MvcSandbox/Models/Index.cs contains only a UTF-8
	// BOM. Linguist 9.7.0 reports C# via Classifier for this ambiguous suffix.
	if language, strategy := DetectLanguage("Index.cs", []byte{0xef, 0xbb, 0xbf}); language != "C#" || strategy != "Classifier" {
		t.Fatalf("BOM-only C# file detected as %q by %q", language, strategy)
	}
	root := fixtures(t, map[string]string{
		"plain.rtf": plainRTF, "sample.rtf": rtf, "main.go": goSource,
		"within.cs": utf16Within, "beyond.cs": utf16Beyond, "late-nul.cs": lateNUL,
	})
	for _, source := range []string{"directory", "auto"} {
		if source == "auto" {
			repo, err := git.PlainInit(root, false)
			if err != nil {
				t.Fatal(err)
			}
			commitFixture(t, root, repo)
		}
		report, err := Scan(context.Background(), root, Options{Source: source, IncludeFiles: true})
		if err != nil {
			t.Fatal(err)
		}
		if !reflect.DeepEqual(languageFiles(report), map[string][]string{"C#": {"beyond.cs", "late-nul.cs", "within.cs"}, "Go": {"main.go"}, "Rich Text Format": {"plain.rtf"}}) {
			t.Fatalf("source %s included late-NUL RTF: %+v", source, report.Languages)
		}
	}
	inspected, err := Inspect(context.Background(), filepath.Join(root, "sample.rtf"), Options{})
	if err != nil {
		t.Fatal(err)
	}
	if !inspected.Binary || inspected.Language != "" {
		t.Fatalf("late-NUL inspection: %+v", inspected)
	}
	for _, filename := range []string{"within.cs", "beyond.cs", "late-nul.cs"} {
		for source, wantBinary := range map[string]bool{
			"directory": filename == "late-nul.cs",
			"git":       false,
		} {
			inspected, err := Inspect(context.Background(), filepath.Join(root, filename), Options{Source: source})
			if err != nil {
				t.Fatal(err)
			}
			if inspected.Binary != wantBinary || (wantBinary && inspected.Language != "") || (!wantBinary && inspected.Language != "C#") {
				t.Fatalf("%s inspection %s: %+v", source, filename, inspected)
			}
		}
	}
}

func TestAttributesNestedOverrides(t *testing.T) {
	root := fixtures(t, map[string]string{
		".gitattributes":     "*.custom linguist-language=Go\nvendor/** linguist-vendored=false\ngenerated.go -linguist-generated\ndata.json linguist-detectable\n.hidden.go linguist-detectable=true\nignore/** linguist-vendored\nsub/*.go linguist-language=Python\nforced.go linguist-generated=true linguist-detectable=true\n",
		"file.custom":        goSource,
		"vendor/lib.go":      goSource,
		"generated.go":       "// Code generated by test. DO NOT EDIT.\n" + goSource,
		"forced.go":          goSource,
		"data.json":          "{}",
		".hidden.go":         goSource,
		"ignore/lib.go":      goSource,
		"sub/.gitattributes": "*.go !linguist-language\n",
		"sub/lib.go":         goSource,
		"z.go":               goSource,
	})
	report, err := Scan(context.Background(), root, Options{IncludeFiles: true})
	if err != nil {
		t.Fatal(err)
	}
	if len(report.Warnings) != 0 {
		t.Fatalf("unexpected warnings: %+v", report.Warnings)
	}
	byLanguage := map[string]profile.Language{}
	for _, language := range report.Languages {
		byLanguage[language.Name] = language
	}
	wantGo := []string{".hidden.go", "file.custom", "generated.go", "sub/lib.go", "vendor/lib.go", "z.go"}
	if !reflect.DeepEqual(byLanguage["Go"].Files, wantGo) {
		t.Fatalf("Go files: %v, want %v", byLanguage["Go"].Files, wantGo)
	}
	if !reflect.DeepEqual(byLanguage["JSON"].Files, []string{"data.json"}) {
		t.Fatalf("JSON: %+v", byLanguage["JSON"])
	}
	if _, ok := byLanguage["Python"]; ok {
		t.Fatal("nested reset did not restore inferred Go")
	}
}

func TestDeterministicWorkersAndPartialDetectorErrors(t *testing.T) {
	files := map[string]string{}
	for i := range 40 {
		files[fmt.Sprintf("dir%d/file%d.go", i%4, i)] = goSource
	}
	root := fixtures(t, files)
	detector := detectorFunc(func(ctx context.Context, file profile.File) ([]profile.Finding, error) {
		findings, _ := observingDetector(ctx, file)
		findings = append(findings, findings[0])
		return findings, errors.New("partial parse")
	})
	var want []byte
	for _, workers := range []int{1, 8, 4, 1} {
		report, err := Scan(context.Background(), root, Options{Workers: workers, IncludeFiles: true, Detectors: []profile.Detector{detector}})
		if err != nil {
			t.Fatal(err)
		}
		if len(report.Ecosystems) != 1 || len(report.Ecosystems[0].Evidence) != 40 || len(report.Warnings) != 40 {
			t.Fatalf("unexpected aggregation: %+v", report)
		}
		encoded, err := json.Marshal(report)
		if err != nil {
			t.Fatal(err)
		}
		if want == nil {
			want = encoded
		} else if string(encoded) != string(want) {
			t.Fatalf("workers=%d yielded different output", workers)
		}
	}
}

func TestSharedImmutableDetectorResults(t *testing.T) {
	files := map[string]string{"main.go": goSource}
	for i := range 20 {
		files[fmt.Sprintf("file%d.go", i)] = goSource
	}
	root := fixtures(t, files)
	shared := []profile.Finding{{Kind: "ecosystem", Name: "shared", Root: ".", Evidence: []string{"main.go"}}}
	detector := detectorFunc(func(context.Context, profile.File) ([]profile.Finding, error) { return shared, nil })
	report, err := Scan(context.Background(), root, Options{Workers: 8, Detectors: []profile.Detector{detector}})
	if err != nil {
		t.Fatal(err)
	}
	if shared[0].Detector != "" || len(shared[0].Evidence) != 1 {
		t.Fatalf("scanner mutated detector-owned findings: %+v", shared)
	}
	if len(report.Ecosystems) != 1 || !reflect.DeepEqual(report.Ecosystems[0].Evidence, []string{"main.go"}) {
		t.Fatalf("unexpected findings: %+v", report.Ecosystems)
	}
}

func TestGeneratedFilesReachHooksWithoutLanguageContribution(t *testing.T) {
	root := fixtures(t, map[string]string{".gitattributes": "forced.go linguist-generated\n", "forced.go": goSource, "package-lock.json": "{}"})
	detector := detectorFunc(func(ctx context.Context, file profile.File) ([]profile.Finding, error) {
		if file.Included {
			return nil, fmt.Errorf("generated file %s counted", file.Path)
		}
		return observingDetector(ctx, file)
	})
	report, err := Scan(context.Background(), root, Options{Detectors: []profile.Detector{detector}})
	if err != nil {
		t.Fatal(err)
	}
	if len(report.Languages) != 0 || len(report.Warnings) != 0 || report.Summary.AnalyzedFiles != 2 {
		t.Fatalf("unexpected report: %+v", report)
	}
	if len(report.Ecosystems) != 1 || len(report.Ecosystems[0].Evidence) != 2 {
		t.Fatalf("missing generated evidence: %+v", report.Ecosystems)
	}
}

func TestCIHooksRespectVendorBoundariesAndOverrides(t *testing.T) {
	root := fixtures(t, map[string]string{
		".gitattributes":                         "excluded/** linguist-vendored=true\n",
		".github/workflows/ci.yml":               "name: ci\n",
		"Jenkinsfile":                            "pipeline {}\n",
		"services/app/.github/workflows/ci.yaml": "name: ci\n",
		"services/app/Jenkinsfile":               "pipeline {}\n",
		"vendor/.github/workflows/ci.yml":        "name: ci\n",
		"vendor/Jenkinsfile":                     "pipeline {}\n",
		"excluded/.github/workflows/ci.yml":      "name: ci\n",
		"excluded/Jenkinsfile":                   "pipeline {}\n",
	})
	detector := detectorFunc(func(ctx context.Context, file profile.File) ([]profile.Finding, error) {
		if file.Included {
			return nil, fmt.Errorf("CI file counted toward languages: %s", file.Path)
		}
		return observingDetector(ctx, file)
	})
	report, err := Scan(context.Background(), root, Options{Detectors: []profile.Detector{detector}})
	if err != nil {
		t.Fatal(err)
	}
	want := []string{".github/workflows/ci.yml", "Jenkinsfile", "services/app/.github/workflows/ci.yaml", "services/app/Jenkinsfile"}
	if len(report.Warnings) != 0 || len(report.Languages) != 0 || len(report.Ecosystems) != 1 || !reflect.DeepEqual(report.Ecosystems[0].Evidence, want) {
		t.Fatalf("CI hook report: %+v", report)
	}
}

func TestUnixFilenameEvidence(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("filenames unsupported by Windows")
	}
	root := fixtures(t, map[string]string{"api:v2/package.json": "{}", "back\\slash/package.json": "{}"})
	report, err := Scan(context.Background(), root, Options{Detectors: []profile.Detector{detectorFunc(observingDetector)}})
	if err != nil {
		t.Fatal(err)
	}
	want := []string{"api:v2/package.json", "back\\slash/package.json"}
	if len(report.Warnings) != 0 || len(report.Ecosystems) != 1 || !reflect.DeepEqual(report.Ecosystems[0].Evidence, want) {
		t.Fatalf("valid Unix names rejected: %+v", report)
	}
}

func TestLimitsSymlinksAndEmptyDirectory(t *testing.T) {
	root := fixtures(t, map[string]string{"big.go": strings.Repeat("x", 101), "main.go": goSource})
	out := fixtures(t, map[string]string{"secret.py": "print('outside')"})
	if err := os.Symlink(filepath.Join(out, "secret.py"), filepath.Join(root, "link.py")); err != nil {
		t.Skipf("symlinks unavailable: %v", err)
	}
	if err := os.Symlink(out, filepath.Join(root, "linked-directory")); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(filepath.Join(out, "secret.py"), filepath.Join(root, ".gitattributes")); err != nil {
		t.Fatal(err)
	}
	report, err := Scan(context.Background(), root, Options{MaxFileBytes: 100, IncludeFiles: true})
	if err != nil {
		t.Fatal(err)
	}
	if report.Summary.ScannedFiles != 5 || report.Summary.SkippedFiles != 4 || report.Summary.AnalyzedFiles != 1 {
		t.Fatalf("summary: %+v", report.Summary)
	}
	if len(report.Languages) != 1 || report.Languages[0].Name != "Go" {
		t.Fatalf("unexpected languages: %+v", report.Languages)
	}
	if len(report.Warnings) != 5 {
		t.Fatalf("warnings: %+v", report.Warnings)
	}
	empty, err := Scan(context.Background(), t.TempDir(), Options{})
	if err != nil {
		t.Fatal(err)
	}
	encoded, err := json.Marshal(empty)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(encoded), "null") || empty.Summary != (profile.Summary{}) {
		t.Fatalf("empty report: %s", encoded)
	}
}

func TestInvalidOptionsAndIOErrors(t *testing.T) {
	for _, opts := range []Options{{Workers: -1}, {Workers: 1025}, {MaxFileBytes: -1}, {MaxFileBytes: 1<<63 - 1}, {Detectors: []profile.Detector{nil}}} {
		if _, err := Scan(context.Background(), t.TempDir(), opts); err == nil {
			t.Fatalf("accepted invalid options: %+v", opts)
		}
	}
	root := fixtures(t, map[string]string{"a.go": goSource, "b.go": goSource})
	if _, err := Scan(context.Background(), filepath.Join(root, "missing"), Options{}); err == nil {
		t.Fatal("missing root accepted")
	}
	if _, err := Scan(context.Background(), filepath.Join(root, "a.go"), Options{}); err == nil {
		t.Fatal("file accepted as root")
	}
	detector := detectorFunc(func(_ context.Context, file profile.File) ([]profile.Finding, error) {
		if file.Path == "a.go" {
			return nil, os.Remove(filepath.Join(root, "b.go"))
		}
		return nil, nil
	})
	if report, err := Scan(context.Background(), root, Options{Workers: 1, Detectors: []profile.Detector{detector}}); err == nil || report != nil {
		t.Fatalf("read failure silently succeeded: report=%+v err=%v", report, err)
	}
}

func TestCancellation(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	if _, err := Scan(ctx, t.TempDir(), Options{}); !errors.Is(err, context.Canceled) {
		t.Fatalf("pre-cancel: %v", err)
	}
	root := fixtures(t, map[string]string{"main.go": goSource})
	ctx, cancel = context.WithCancel(context.Background())
	defer cancel()
	detector := detectorFunc(func(context.Context, profile.File) ([]profile.Finding, error) { cancel(); return nil, context.Canceled })
	if _, err := Scan(ctx, root, Options{Detectors: []profile.Detector{detector}}); !errors.Is(err, context.Canceled) {
		t.Fatalf("mid-scan cancellation: %v", err)
	}
}

func TestInvalidFindingsBecomeWarnings(t *testing.T) {
	root := fixtures(t, map[string]string{"main.go": goSource})
	detector := detectorFunc(func(context.Context, profile.File) ([]profile.Finding, error) {
		return []profile.Finding{
			{Kind: "ecosystem", Name: "", Evidence: []string{"main.go"}},
			{Kind: "ecosystem", Name: "bad-root", Root: "../outside", Evidence: []string{"main.go"}},
			{Kind: "ecosystem", Name: "no-evidence"},
			{Kind: "ecosystem", Name: "bad-evidence", Evidence: []string{"/etc/passwd"}},
			{Kind: "other", Name: "bad-kind", Evidence: []string{"main.go"}},
		}, nil
	})
	report, err := Scan(context.Background(), root, Options{Detectors: []profile.Detector{detector}})
	if err != nil {
		t.Fatal(err)
	}
	if len(report.Warnings) != 5 || len(report.Ecosystems) != 0 {
		t.Fatalf("invalid findings retained: %+v", report)
	}
}

func TestReadBoundedGrowingSizeAndAttributeLimit(t *testing.T) {
	rootPath := fixtures(t, map[string]string{"main.go": goSource, ".gitattributes": strings.Repeat("#", int(maxAttributesBytes)+1)})
	root, err := os.OpenRoot(rootPath)
	if err != nil {
		t.Fatal(err)
	}
	defer root.Close()
	value, err := analyzeFile(context.Background(), root, job{path: "main.go", size: 1}, Options{MaxFileBytes: 5})
	if err != nil {
		t.Fatal(err)
	}
	if !value.skipped || len(value.warnings) != 1 {
		t.Fatalf("growing file was prefix-classified: %+v", value)
	}
	report, err := Scan(context.Background(), rootPath, Options{})
	if err != nil {
		t.Fatal(err)
	}
	if len(report.Warnings) != 1 {
		t.Fatalf("oversized attrs not surfaced: %+v", report.Warnings)
	}
}

func BenchmarkScan(b *testing.B) {
	files := map[string]string{}
	for i := range 100 {
		files[fmt.Sprintf("src/%04d.go", i)] = goSource + strings.Repeat("// representative source\n", 80)
	}
	root := fixtures(b, files)
	for _, workers := range []int{1, 4} {
		b.Run(fmt.Sprintf("workers-%d", workers), func(b *testing.B) {
			b.ReportAllocs()
			b.SetBytes(int64(100 * len(files["src/0000.go"])))
			for b.Loop() {
				if _, err := Scan(context.Background(), root, Options{Workers: workers}); err != nil {
					b.Fatal(err)
				}
			}
		})
	}
}

func TestDirectoryTreeLimitIsNotPartial(t *testing.T) {
	root := fixtures(t, map[string]string{"main.go": goSource, "sub/script.py": "print('hello')\n", ".git/config": "ignored metadata"})
	for _, workers := range []int{1, 16} {
		report, err := Scan(context.Background(), root, Options{Source: "directory", Workers: workers, MaxTreeSize: 2})
		if err != nil {
			t.Fatal(err)
		}
		if len(report.Languages) != 0 || report.Summary != (profile.Summary{}) || len(report.Warnings) != 1 || report.Warnings[0].Code != "tree_size_limit" {
			t.Fatalf("partial report: %+v", report)
		}
	}
	report, err := Scan(context.Background(), root, Options{Source: "directory", MaxTreeSize: 3})
	if err != nil {
		t.Fatal(err)
	}
	if len(report.Languages) != 2 {
		t.Fatalf("tree below limit suppressed: %+v", report)
	}
}

func TestDirectoryAttributeRuleLimit(t *testing.T) {
	root := fixtures(t, map[string]string{
		".gitattributes": strings.Repeat("*.go linguist-generated\n", maxAttributeRules+1),
		"main.go":        goSource,
	})
	report, err := Scan(context.Background(), root, Options{Source: "directory"})
	if err != nil || len(report.Warnings) != 1 || report.Warnings[0].Code != "unsupported_gitattributes" || len(report.Languages) != 1 {
		t.Fatalf("attribute rule limit was not disclosed: report=%+v err=%v", report, err)
	}
}
