package scanner

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
	"time"

	"dircue/pkg/profile"
	"dircue/pkg/structure"
)

func nativeStructure(t *testing.T, limit int64, timeout time.Duration) *structure.Client {
	t.Helper()
	worker := os.Getenv("DIRCUE_STRUCTURAL_WORKER")
	if worker == "" {
		t.Skip("native structural worker not supplied")
	}
	client, err := structure.New(structure.Options{Worker: worker, MaxFileBytes: limit, Timeout: timeout})
	if err != nil {
		t.Fatal(err)
	}
	return client
}
func structureFiles(t *testing.T, r *profile.Report) map[string]structure.File {
	t.Helper()
	if r.Structure == nil || r.Structure.Files == nil {
		t.Fatal("missing structure file detail")
	}
	files := map[string]structure.File{}
	for _, file := range *r.Structure.Files {
		files[file.Path] = file
	}
	return files
}

func TestStructureNativeGitSnapshotAndFullSource(t *testing.T) {
	client := nativeStructure(t, 0, 0)
	content := "class First {}\n" + strings.Repeat(" \n", int(ClassificationBytes)) + "class Last { int f() { return 1; } }\n"
	root, repo, revision := gitFixture(t, map[string]string{"A.java": content})
	if err := os.WriteFile(filepath.Join(root, "A.java"), []byte("class Dirty {}"), 0644); err != nil {
		t.Fatal(err)
	}
	for _, source := range []string{"git", "directory"} {
		r, err := Scan(context.Background(), root, Options{Source: source, Structure: client, StructureFiles: true})
		if err != nil {
			t.Fatal(err)
		}
		file := structureFiles(t, r)["A.java"]
		want := uint64(2)
		if source == "directory" {
			want = 1
		}
		if file.Observations["classes"] != want || file.ParseCount != 1 || r.Structure.AnalyzedFiles != 1 || r.Structure.Status != "complete" {
			t.Fatalf("%s: %+v %+v", source, file, r.Structure)
		}
		if r.Structure.Source != source {
			t.Fatal("incorrect source attribution")
		}
		if source == "git" {
			commit, err := repo.CommitObject(revision)
			if err != nil {
				t.Fatal(err)
			}
			if r.Structure.Tree != commit.TreeHash.String() {
				t.Fatal("incorrect Git tree")
			}
		}
	}
}

func TestStructureNativeScopeAndAttributeOverrides(t *testing.T) {
	client := nativeStructure(t, 0, 0)
	root := fixtures(t, map[string]string{
		"A.cs":             "class A { int F() { return 1; } }",
		"generated.cs":     "class Generated {}",
		"restored.cs":      "// <auto-generated>\nclass Restored {}",
		"vendor/forced.cs": "class VendorOverride {}",
		"vendor/skip.cs":   "class VendorSkip {}",
		"data.xml":         "<log>not source code</log>",
		".gitattributes":   "generated.cs linguist-generated=true\nrestored.cs linguist-generated=false\nvendor/forced.cs linguist-vendored=false\n",
	})
	base, err := Scan(context.Background(), root, Options{Source: "directory"})
	if err != nil {
		t.Fatal(err)
	}
	r, err := Scan(context.Background(), root, Options{Source: "directory", Structure: client, StructureFiles: true})
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(base.Languages, r.Languages) || base.Summary != r.Summary {
		t.Fatal("structure changed language profiling")
	}
	if r.Structure.AnalyzedFiles != 3 || r.Structure.ParseCount != 3 || r.Structure.Status != "complete" {
		t.Fatalf("scope: %+v", r.Structure)
	}
	files := structureFiles(t, r)
	for _, path := range []string{"A.cs", "restored.cs", "vendor/forced.cs"} {
		if files[path].Status != "complete" {
			t.Fatalf("override lost: %s %+v", path, files[path])
		}
	}
	for _, path := range []string{"generated.cs", "data.xml"} {
		if files[path].Status != "skipped" || files[path].Reason != "outside_scope" {
			t.Fatalf("scope lost: %s %+v", path, files[path])
		}
	}
}

func TestStructureNativeCoverageAndLimits(t *testing.T) {
	client := nativeStructure(t, 32, 0)
	for _, tc := range []struct {
		name           string
		files          map[string]string
		status, reason string
		analyzed       int64
	}{
		{"no source", map[string]string{"README.md": "# docs"}, "skipped", "outside_scope", 0},
		{"unsupported source", map[string]string{"main.swift": "func hello() {}\n"}, "partial", "unsupported_language", 0},
		{"source cap", map[string]string{"A.java": "class A { int f() { return 1111111111111111111; } }"}, "partial", "file_too_large", 0},
		{"grammar recovery", map[string]string{"A.java": "class {"}, "partial", "", 1},
	} {
		t.Run(tc.name, func(t *testing.T) {
			r, err := Scan(context.Background(), fixtures(t, tc.files), Options{Source: "directory", Structure: client, StructureFiles: true})
			if err != nil {
				t.Fatal(err)
			}
			if r.Structure.Status != tc.status || r.Structure.AnalyzedFiles != tc.analyzed {
				t.Fatalf("coverage: %+v", r.Structure)
			}
			if tc.reason != "" && r.Structure.Omissions[tc.reason] != 1 {
				t.Fatalf("omission: %+v", r.Structure)
			}
		})
	}
}

func TestStructureNativeWorkerTimeoutIsFatal(t *testing.T) {
	client := nativeStructure(t, 0, time.Nanosecond)
	root := fixtures(t, map[string]string{"A.java": "class A {}"})
	r, err := Scan(context.Background(), root, Options{Source: "directory", Structure: client})
	if !errors.Is(err, context.DeadlineExceeded) || r != nil {
		t.Fatalf("worker deadline became success: %+v %v", r, err)
	}
}

func TestStructureNativeGlobalInputCapIsPartial(t *testing.T) {
	client := nativeStructure(t, 0, 0)
	source := "class A { int F() { return 1; } }"
	root := fixtures(t, map[string]string{"A.cs": source})
	r, err := Scan(context.Background(), root, Options{Source: "directory", MaxFileBytes: 8, Structure: client, StructureFiles: true})
	if err != nil {
		t.Fatal(err)
	}
	if r.Structure.Status != "partial" || r.Structure.AnalyzedFiles != 0 || r.Structure.ParseCount != 0 || r.Structure.Omissions["file_too_large"] != 1 {
		t.Fatalf("global cap hidden from coverage: %+v", r.Structure)
	}
	file := structureFiles(t, r)["A.cs"]
	if file.Status != "skipped" || file.Reason != "file_too_large" {
		t.Fatalf("missing omission detail: %+v", file)
	}
}

func TestStructureNativeReusesMetricsFullRead(t *testing.T) {
	client := nativeStructure(t, 0, 0)
	content := []byte("class A {\n" + strings.Repeat(" // comment\n", int(ClassificationBytes/8)) + " int f() { return 1; } }\n")
	calls := 0
	item := job{path: "A.java", size: int64(len(content)), read: func(limit int64) ([]byte, int64, error) {
		calls++
		return content[:min(int64(len(content)), limit)], int64(len(content)), nil
	}}
	value, err := analyzeFile(context.Background(), nil, item, Options{
		Projects:      true,
		Metrics:       &MetricsOptions{Scope: "source", MaxFileBytes: DefaultMetricsMaxFileBytes},
		Structure:     client,
		structureGate: make(chan struct{}, 1),
	})
	if err != nil {
		t.Fatal(err)
	}
	if calls != 2 {
		t.Fatalf("expected one classification read and one shared full read, got %d", calls)
	}
	if value.metrics == nil || value.metrics.Status != "counted" || value.metrics.Counts.Bytes != int64(len(content)) {
		t.Fatalf("incomplete metrics: %+v", value.metrics)
	}
	if value.structural == nil || value.structural.ParseCount != 1 || value.structural.SourceBytes != int64(len(content)) || value.structural.Observations["methods"] != 1 {
		t.Fatalf("incomplete structure: %+v", value.structural)
	}
}

func TestStructureNativeExpandedLanguages(t *testing.T) {
	client := nativeStructure(t, 0, 0)
	root := fixtures(t, map[string]string{
		"A.java":     "class A {}\n",
		"main.go":    "package main\nfunc main() {}\n",
		"main.py":    "def hello():\n    return 1\n",
		"app.tsx":    "export const App = () => <div>Hello</div>;\n",
		"hello.sh":   "#!/bin/bash\necho hello\n",
		"readme.xml": "<log>data</log>\n",
	})
	base, err := Scan(context.Background(), root, Options{Source: "directory"})
	if err != nil {
		t.Fatal(err)
	}
	var first *profile.StructureReport
	for _, workers := range []int{1, 8} {
		r, err := Scan(context.Background(), root, Options{Source: "directory", Workers: workers, Structure: client, StructureFiles: true})
		if err != nil {
			t.Fatal(err)
		}
		if !reflect.DeepEqual(base.Languages, r.Languages) || base.Summary != r.Summary {
			t.Fatal("expanded structure changed language results")
		}
		if r.Structure.AnalyzedFiles != 5 || r.Structure.ParseCount != 5 || r.Structure.Status != "complete" {
			t.Fatalf("coverage: %+v", r.Structure)
		}
		if r.Structure.ObservationFiles["classes"] != 1 || r.Structure.ObservationFiles["syntax_nodes"] != 5 {
			t.Fatalf("observation coverage: %+v", r.Structure.ObservationFiles)
		}
		if !reflect.DeepEqual(r.Structure.SupportedLanguages, structure.Capabilities()) {
			t.Fatal("capabilities missing")
		}
		for _, path := range []string{"main.go", "main.py", "app.tsx", "hello.sh"} {
			file := structureFiles(t, r)[path]
			if file.Status != "complete" || len(file.Observations) != 3 || file.Provenance == nil {
				t.Fatalf("%s: %+v", path, file)
			}
			if _, exists := file.Observations["classes"]; exists {
				t.Fatalf("unavailable observation for %s", path)
			}
		}
		if first != nil && !reflect.DeepEqual(first, r.Structure) {
			t.Fatal("worker count changed structure output")
		}
		first = r.Structure
	}
}
