#!/usr/bin/env python3
"""Collect upstream license files for modules linked into the CLI."""
import json
import os
from pathlib import Path
import subprocess

root = Path(__file__).resolve().parents[1]
decoder = json.JSONDecoder()
modules = {}
for target_os, architecture in [("linux", "amd64"), ("linux", "arm64"), ("darwin", "amd64"), ("darwin", "arm64"), ("windows", "amd64")]:
    environment = {**os.environ, "CGO_ENABLED": "0", "GOOS": target_os, "GOARCH": architecture}
    stream = subprocess.check_output(["go", "list", "-deps", "-json", "."], cwd=root, env=environment, text=True)
    while stream.strip():
        stream = stream.lstrip()
        package, offset = decoder.raw_decode(stream)
        stream = stream[offset:]
        module = package.get("Module")
        if module and not module.get("Main"):
            modules[module["Path"]] = module
sections = ["# Third-party notices\n\nGenerated by `python3 scripts/notices.py` from modules linked into dircue across all five release targets and the explicitly listed embedded source snapshots. Test-only dependencies are excluded.\n"]
goroot = Path(subprocess.check_output(["go", "env", "GOROOT"], cwd=root, text=True).strip())
sections.append("## Go standard library and runtime\n\n```text\n" + (goroot / "LICENSE").read_text() + "\n```\n")
for name, module in sorted(modules.items()):
    directory = Path(module["Dir"])
    licenses = [entry for entry in directory.iterdir() if entry.is_file() and (
        entry.name.upper().startswith(("LICENSE", "LICENCE", "COPYING", "NOTICE")) or entry.name == "LINGUIST_LICENSE")]
    if not licenses:
        raise RuntimeError(f"no root license located for linked module {name}")
    version = module.get("Version", "local")
    if module.get("Replace"):
        replacement = Path(module["Replace"]["Dir"]).relative_to(root)
        version += f" (maintained copy; see {replacement.as_posix()}/PROVENANCE.json)"
    sections.append(f"## {name} {version}\n")
    for license in sorted(licenses):
        sections.append(f"### {license.name}\n\n```text\n{license.read_text(errors='replace')}\n```\n")
embedded = [
    ("github.com/go-enry/go-enry/v2", "v2.9.6", "third_party/go-enry", ["LICENSE", "LINGUIST_LICENSE"]),
    ("github.com/go-git/go-git/v5", "v5.19.2", "third_party/go-git", ["LICENSE"]),
    ("github.com/boyter/scc/v4", "v4.1.0", "third_party/scc", ["LICENSE"]),
]
for module, version, relative, license_names in embedded:
    component = root / relative
    provenance = component / "PROVENANCE.json"
    if module != "github.com/boyter/scc/v4" and not provenance.is_file():
        raise RuntimeError(f"missing provenance for embedded source {module}: {provenance}")
    source_note = (f"; see `{relative}/PROVENANCE.json`" if provenance.is_file()
                   else "; source pin documented in `docs/SCC_UPSTREAM.md`")
    sections.append(f"## {module} {version} (embedded source{source_note})\n")
    for license_name in license_names:
        license = component / license_name
        if not license.is_file():
            raise RuntimeError(f"missing required license for {module}: {license}")
        sections.append(f"### {license_name}\n\n```text\n{license.read_text(errors='replace')}\n```\n")
sections.append("## github.com/santhosh-tekuri/jsonschema/v5 v5.3.1 (private maintained copy)\n\nThe private runtime in `internal/jsonschema` defers bundled metaschema compilation until first use. Its validation logic is unchanged. See `internal/jsonschema/PROVENANCE.json` for the pinned upstream source, retained file hashes and patch.\n\n```text\n" + (root / "internal/jsonschema/LICENSE").read_text() + "\n```\n")
sections.append("## mini_mime 1.1.5 extension database\n\n```text\n" + (root / "internal/cli/mimedata/LICENSE.txt").read_text() + "\n```\n")
sections.append("## Charlock Holmes 0.7.9 binary detection policy\n\nThe scanner's Go binary preflight follows the MIT-licensed raw-byte policy in `brianmario/charlock_holmes` v0.7.9, `ext/charlock_holmes/encoding_detector.c`. No Charlock or ICU runtime is linked.\n\n```text\n" + (root / "third_party/CHARLOCK_LICENSE").read_text() + "\n```\n")
(root / "THIRD_PARTY_NOTICES.md").write_text("\n".join(sections))
