// Package atlas embeds the accuracy cards data generated by make accuracy-cards
// and exposes it for the dircue capabilities --accuracy command.
//
// The data file is generated from hand-labeled ground truth in
// tests/map_corpus/public_quality_expectations.json. Run make accuracy-cards to
// regenerate it before a release.
package atlas

import (
	_ "embed"
	"encoding/json"
	"fmt"
)

//go:embed accuracy_data.json
var accuracyDataJSON []byte

// AccuracyCards is the top-level structure of the embedded accuracy cards.
type AccuracyCards struct {
	SchemaVersion  string               `json:"schema_version"`
	GeneratedAtUTC string               `json:"generated_at_utc"`
	EvaluatedRepos int                  `json:"evaluated_repos"`
	LabelSource    string               `json:"label_source"`
	ScopeNote      string               `json:"scope_note"`
	Overall        map[string]KindScore `json:"overall"`
	PerRepo        []RepoScore          `json:"per_repo"`
	Notes          []string             `json:"notes,omitempty"`
}

// KindScore holds precision/recall statistics for one map question kind.
type KindScore struct {
	TP            int       `json:"tp"`
	FP            int       `json:"fp"`
	FN            int       `json:"fn"`
	Precision     *float64  `json:"precision"`
	Recall        *float64  `json:"recall"`
	PrecisionCI95 []float64 `json:"precision_ci_95,omitempty"`
	RecallCI95    []float64 `json:"recall_ci_95,omitempty"`
	// CILower is the Wilson 95% lower bound on precision.
	// Use this as the conservative headline figure; it is narrow for small label sets.
	CILower *float64 `json:"ci_lower,omitempty"`
	// Sufficiency is "sufficient" when LabelCount >= 30, otherwise "insufficient_labels".
	// Kinds marked insufficient_labels are directional only; confidence intervals are wide.
	Sufficiency string  `json:"sufficiency,omitempty"`
	LabelCount  int     `json:"label_count"`
	RepoCount   int     `json:"repo_count,omitempty"`
	Note        *string `json:"note,omitempty"`
}

// RepoScore holds per-repository kind scores.
type RepoScore struct {
	RepoID string               `json:"repo_id"`
	Commit string               `json:"commit"`
	Scores map[string]KindScore `json:"scores"`
	Note   *string              `json:"note,omitempty"`
}

// Load parses the embedded accuracy cards JSON and returns the cards.
// It does not access the network or the filesystem; the data is compiled in.
func Load() (*AccuracyCards, error) {
	var cards AccuracyCards
	if err := json.Unmarshal(accuracyDataJSON, &cards); err != nil {
		return nil, fmt.Errorf("accuracy cards: %w", err)
	}
	return &cards, nil
}

// RawJSON returns the raw embedded JSON bytes without parsing. Callers who
// want to stream the JSON to stdout can avoid an extra encode/decode cycle.
func RawJSON() []byte {
	return accuracyDataJSON
}
